<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 분석 & 머신 러닝 패키지(라이브러리)

*   NumPy: 다차원 배열(ndarray)을 쉽게 사용할 수 있도록 만들어진 패키지. 머신러닝에서 중요하게 사용됨.
*   pandas: 시리즈(Series)와 데이터프레임(DataFrame)을 기본으로 사용해서 데이터 분석에 필요한 기능들을 가지고 있는 패키지.
*   matplotlib, seaborn: 데이터 시각화(그래프, 차트) 패키지.
*   scikit-learn: 머신 러닝(Machine Learning) 패키지.
*   keras: 딥 러닝(Deep Learning) 패키지.


In [1]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
import sklearn  # scikit-learn 패키지
import keras

In [3]:
# 현재 Colab 런타임에 설치된 각 패키지의 버전들
print('NumPy version =', np.__version__)
print('pandas version =', pd.__version__)
print('matplotlib version =', matplotlib.__version__)
print('seaborn version =', sns.__version__)
print('scikit-learn version =', sklearn.__version__)
print('keras version =', keras.__version__)

NumPy version = 2.0.2
pandas version = 2.2.2
matplotlib version = 3.10.0
seaborn version = 0.13.2
scikit-learn version = 1.6.1
keras version = 3.13.2


# Python `list` 클래스

*   여러 개의 값들을 저장할 수 있는 데이터 타입.
*   인덱스 기반 데이터 타입
    *   인덱스: 리스트에 아이템들이 저장된 순서(위치)를 표시하는 정수.
    *   indexing: 인덱스를 사용해서 리스트의 특정 위치의 값을 참조. (예) `list[0]`
    *   slicing: [start, end) 인덱스 범위의 아이템들을 잘라낸 리스트. (예) `list[0:5]`
*   산술 연산
    *   `list + list`: concatenate.
    *   `list * int, int * list`: replicate.

In [4]:
list1 = [1, 2, 3]
list2 = [11, 22, 33]

In [5]:
print(list1)  #> list.__str__() 메서드가 리턴하는 문자열

[1, 2, 3]


In [6]:
list1  #> list.__repr__() 메서드가 리턴하는 문자열

[1, 2, 3]

In [7]:
# indexing
print(list1[0])
print(list1[-1])

1
3


In [8]:
# slicing
print(list1[:2])
print(list1[-2:])

[1, 2]
[2, 3]


In [9]:
print(list1[:1])

[1]


In [10]:
list1 + list2  # list1.extend(list2)와 동일.

[1, 2, 3, 11, 22, 33]

In [11]:
[x + y for x, y in zip(list1, list2)]

[12, 24, 36]

In [12]:
list1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
[3 * x for x in list1]

[3, 6, 9]

# NumPy(Numerical Python)

*   `numpy.ndarray` 클래스: numpy 패키지의 가장 기본이 되는 클래스.
*   다차원 배열(n-dimensinal array)을 쉽고 빠르게 연산(+, -, *, /, ...)하기 위한 패키지.
*   numpy 패키지의 대부분의 기능들(연산자, 함수, 메서드 등)은 반복문의 기능을 가지고 있음.
    *   같은 인덱스의 원소들끼지(element-wise) 연산하는 기능을 가지고 있음.

In [14]:
array1 = np.array([1, 2, 3, 4, 5])  # list를 ndarray로 변환해서 리턴

In [15]:
type(array1)

numpy.ndarray

In [16]:
print(array1)  #> numpy.ndarray.__str__()

[1 2 3 4 5]


In [17]:
array1  # numpy.ndarray.__repr__()

array([1, 2, 3, 4, 5])

In [18]:
array2 = np.array([10, 20, 30, 40, 50])

In [22]:
# element-wise operation(같은 인덱스의 원소들끼리 연산)
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [23]:
print(array1 + 1)

[2 3 4 5 6]


In [24]:
print(array1 * 2)

[ 2  4  6  8 10]


# `numpy.ndarray` 클래스의 속성들(attributes)

In [25]:
print(array1)
print('ndim =', array1.ndim)  # number of dimensions(차원 개수)
print('size =', array1.size)  # 크기(모든 원소들의 개수)
print('shape =', array1.shape)  # 모양(배열의 각 차원의 원소 개수들로 이루어진 튜플)
print('dtype =', array1.dtype)  # data type(배열 원소의 데이터 타입)

[1 2 3 4 5]
ndim = 1
size = 5
shape = (5,)
dtype = int64


*   Python 숫자 타입
    *   정수: int
    *   실수: float

*   numpy 숫자 타입
    *   정수: int8, int16, int32, int64, ...
    *   실수: float16, float32, float64, ...

In [26]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print('ndim =', array_2d.ndim)
print('size =', array_2d.size)
print('shape =', array_2d.shape)
print('dtype =', array_2d.dtype)

ndim = 2
size = 6
shape = (2, 3)
dtype = int64


# `numpy.ndarray` 객체 생성 함수들

## `numpy.array(object)`

*   object를 numpy.ndarray 객체로 변환해서 리턴.
*   object: 배열과 비슷한 객체들. (예) list, tuple, ndarray, ...

In [30]:
# 0 이상 10 미만의 정수들로 이루어진 ndarray
numbers = np.array([x for x in range(10)])
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


## `numpy.arange(start, end, step)`

*   range를 사용해서 배열을 만들어 주는 함수
*   파이썬의 range() 함수 사용법과 같음.
*   1차원 배열을 생성.

In [31]:
numbers = np.arange(10)  # 0 <= x < 10 범위의 1씩 증가하는 정수들의 배열
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# 0 이상 10 미만의 짝수들을 갖는 배열
evens = np.arange(0, 10, 2)
print(evens)

[0 2 4 6 8]


## reshape

*   `numpy.reshape(array, newshape)` 함수(function)
*   `numpy.ndarray.reshape(newshape)` 메서드(method)

In [34]:
array = np.arange(1, 13)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
array2 = np.reshape(array, (3, 4))  # 함수 호출
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
array3 = array.reshape((3, 4))  # 객체에서 메서드 호출
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
array4 = array.reshape((4, 3))
print(array4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
array4.reshape((12,))  # 2차원 배열 --> 1차원 배열

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
# 메서드 연쇄 호출
array = np.arange(15).reshape((3, 5))
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 난수 배열

### `numpy.random.rand(d0, d1, d2, ...)`

*   [0, 1) 범위의 균등분포(uniform distribution)를 따르는 난수들의 배열을 만듦.
*   아규먼트(d0, d1, ...)들은 각 차원의 원소 개수를 의미.

In [42]:
array = np.random.rand(5)
print(array)

[0.28818479 0.43730772 0.6657483  0.52072298 0.77914151]


In [44]:
array = np.random.rand(3, 5)
print(array)

[[0.17699497 0.54368022 0.71538591 0.99795525 0.02761663]
 [0.35562205 0.22014171 0.19325728 0.91541092 0.6709433 ]
 [0.53731121 0.92543801 0.8044268  0.62936643 0.24610584]]


### `numpy.random.randn(d0, d1, d2, ...)`

*   평균이 0이고 표준편차가 1인 표준정규분포(standard normal distribution)를 따르는 난수들의 배열을 만듦.
*   아규먼트(d0, d1, ...)들은 각 차원의 원소의 개수.

In [48]:
array = np.random.randn(5)
print(array)

[ 1.7040769  -0.05767084  0.35696989 -0.78181632 -1.06663873]


In [49]:
array = np.random.randn(5, 3)
print(array)

[[ 0.97549292  0.4395617  -0.58798662]
 [-1.23059657 -1.18586012 -0.0634299 ]
 [-0.85657163  1.01209034 -1.09622697]
 [ 0.24671685 -1.15118953  0.78261382]
 [ 0.08088707  1.40184261 -0.83691375]]
