<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da11_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Series 인덱스

## 단일 계층 인덱스

In [2]:
s = pd.Series(data=np.random.rand(5), name='value')
#> Series 객체도 데이터프레임의 컬럼처럼 값들의 이름을 설정할 수 있음.

In [3]:
s

,value
0,0.358603
1,0.459944
2,0.621729
3,0.045991
4,0.951872


In [4]:
s.index  #> Series의 index 속성 - RangeIndex

RangeIndex(start=0, stop=5, step=1)

In [5]:
s.values  #> Series의 values 속성 - 값들을 원소로 갖는 1차원 배열(numpy.ndarray)

array([0.35860288, 0.45994388, 0.62172889, 0.04599117, 0.95187214])

In [6]:
scores = pd.Series(data=np.random.randint(101, size=5),
                   index=['scott', 'tiger', 'king', 'allen', '홍길동'],
                   name='score')

In [7]:
scores

,score
scott,57
tiger,2
king,17
allen,52
홍길동,51


In [8]:
scores.index  #> Index 객체

Index(['scott', 'tiger', 'king', 'allen', '홍길동'], dtype='object')

In [9]:
scores.index.nlevels

1

In [10]:
scores.values  #> ndarray 객체

array([57,  2, 17, 52, 51])

In [11]:
scores['scott']  # scores.loc['scott']

np.int64(57)

In [12]:
scores[['scott', '홍길동']]

,score
scott,57
홍길동,51


## 계층적 인덱스(hierachical index, multi-level index)

In [13]:
scores2 = pd.Series(data=np.random.randint(101, size=6),
                    name='score',
                    index=[[1, 1, 1, 2, 2, 2], [1, 2, 3, 1, 2, 3]])
scores2

1  1    51
   2    58
   3    95
2  1    18
   2    33
   3    17
Name: score, dtype: int64

In [14]:
scores2.values

array([51, 58, 95, 18, 33, 17])

In [15]:
scores2.index  #> MultiIndex 객체

MultiIndex([(1, 1),
            (1, 2),
            (1, 3),
            (2, 1),
            (2, 2),
            (2, 3)],
           )

Multi-level index에서 indexing과 slicing

*   첫번째 계층(level)의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층(level)의 인덱스만 가지고는 indexing과 slicing은 할 수 없음.
*   튜플 형태의 인덱스로는 indexing과 slicing을 할 수 있음.


In [16]:
scores2.index.nlevels

2

In [17]:
scores2.loc[1]  # scores[1]

,score
1,51
2,58
3,95


In [18]:
scores2.loc[2]  # scores[2]

,score
1,18
2,33
3,17


In [19]:
scores2.loc[1:2]

1  1    51
   2    58
   3    95
2  1    18
   2    33
   3    17
Name: score, dtype: int64

In [20]:
scores2[(1, 3)]  # indexing

np.int64(95)

In [21]:
scores2[[(1, 3), (2, 3)]]  # fancy indexing

,,score
1,3,95
2,3,17


In [22]:
scores2[(1, 2):(2, 2)]  # slicing

1  2    58
   3    95
2  1    18
   2    33
Name: score, dtype: int64

계층적 인덱스에서 인덱스의 순서 바꾸기

In [23]:
scores2.swaplevel()

,,score
1,1,51
2,1,58
3,1,95
1,2,18
2,2,33
3,2,17


In [24]:
# nlevels=3인 인덱스를 갖는 시리즈
np.random.seed(42)
s = pd.Series(data=np.random.rand(6),
              index=[np.arange(1, 7),
                     ['A'] * 3 + ['B'] * 3,
                     ['a', 'b', 'c'] * 2])
s

,,,0
1,A,a,0.374540
2,A,b,0.950714
3,A,c,0.731994
4,B,a,0.598658
5,B,b,0.156019
6,B,c,0.155995


In [25]:
s.loc[1:3]

,,,0
1,A,a,0.374540
2,A,b,0.950714
3,A,c,0.731994


In [26]:
s.swaplevel()
# 파라미터 i=-2, j=-1 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈(swap).

,,,0
1,a,A,0.374540
2,b,A,0.950714
3,c,A,0.731994
4,a,B,0.598658
5,b,B,0.156019
6,c,B,0.155995


In [27]:
s.swaplevel(i=1, j=2)

,,,0
1,a,A,0.374540
2,b,A,0.950714
3,c,A,0.731994
4,a,B,0.598658
5,b,B,0.156019
6,c,B,0.155995


In [28]:
s.swaplevel(i=0, j=1)  # 첫번째 인덱스와 두번째 인덱스를 서로 바꿈(swap).

A  1  a    0.374540
   2  b    0.950714
   3  c    0.731994
B  4  a    0.598658
   5  b    0.156019
   6  c    0.155995
dtype: float64

# DataFrame 인덱스

In [29]:
np.random.seed(42)
df = pd.DataFrame(data=np.random.randint(100, size=(6, 3)),
                  columns=['total_bill', 'tip', 'size'],
                  index=[['Fri', 'Fri', 'Sat', 'Sat', 'Sun', 'Sun'],
                         ['Lunch', 'Dinner'] * 3])
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [30]:
df.values  #> numpy.ndarray

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99],
       [23,  2, 21],
       [52,  1, 87]])

In [31]:
df.index  #> MultiIndex: 튜플들의 배열.

MultiIndex([('Fri',  'Lunch'),
            ('Fri', 'Dinner'),
            ('Sat',  'Lunch'),
            ('Sat', 'Dinner'),
            ('Sun',  'Lunch'),
            ('Sun', 'Dinner')],
           )

In [32]:
df.index.nlevels

2

In [33]:
df.loc['Fri']  #> 첫번째 레벨의 인덱스만 가지고도 indexing을 할 수 있음.

,total_bill,tip,size
Lunch,51,92,14
Dinner,71,60,20


In [ ]:
# df.loc['Lunch']  #> 두번째 이상 레벨의 인덱스만 가지고는 indexing을 할 수 없음.

In [35]:
df.loc[('Fri', 'Lunch')]  #> 다중 인덱스 튜플을 사용한 indexing.

,Fri
,Lunch
total_bill,51
tip,92
size,14


In [36]:
df.loc[['Sat', 'Sun']]  #> 첫번째 레벨의 인덱스들을 사용한 fancy indexing.

total_bill  tip  size
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [37]:
df.loc[[('Fri', 'Lunch'), ('Sat', 'Lunch'), ('Sun', 'Lunch')]]
#> 다중 인덱스 튜플들을 사용한 fancy indexing.

,,total_bill,tip,size
Fri,Lunch,51,92,14
Sat,Lunch,82,86,74
Sun,Lunch,23,2,21


In [40]:
df.swaplevel().loc['Lunch']

,total_bill,tip,size
Fri,51,92,14
Sat,82,86,74
Sun,23,2,21


# DataFrame column <---> DataFrame index

*   `pandas.DataFrame.set_index()`: 데이터프레임의 컬럼(들)을 인덱스로 변환.
*   `pandas.DataFrame.reset_index()`: 데이터프레임 (행) 인덱스를 데이터프레임의 컬럼으로 변환.

In [41]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

## reset_index

In [42]:
df.reset_index()  #> 인덱스들을 컬럼으로 리셋한 새로운 데이터프레임을 리턴. 원본 유지.

,level_0,level_1,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [44]:
df.reset_index(names=['day', 'time'])

,day,time,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [59]:
# 특정 레벨의 인덱스만 컬럼으로 변환
df.reset_index(level=0, names=['day', 'time'])

,day,total_bill,tip,size
Lunch,Fri,51,92,14
Dinner,Fri,71,60,20
Lunch,Sat,82,86,74
Dinner,Sat,74,87,99
Lunch,Sun,23,2,21
Dinner,Sun,52,1,87


In [58]:
df.reset_index(level=-1, names=['day', 'time'])

,time,total_bill,tip,size
Fri,Lunch,51,92,14
Fri,Dinner,71,60,20
Sat,Lunch,82,86,74
Sat,Dinner,74,87,99
Sun,Lunch,23,2,21
Sun,Dinner,52,1,87
