<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

In [2]:
# Colab의 numpy 버전
np.__version__

'2.0.2'

# `numpy.ndarray` 클래스의 속성들(properties)

In [3]:
# 1차원 배열
arr = np.arange(10)
print(arr)
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (10,)
size: 10
ndim: 1
dtype: int64


In [5]:
# 2차원 배열
arr = np.ones(shape=(2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (2, 3)
size: 6
ndim: 2
dtype: float64


In [9]:
# 3차원 배열(2차원 배열들을 원소로 갖는 배열)
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(arr[0, 0])  # print(arr[0][0])

[1 2 3 4]


In [13]:
print(arr[0, 0, 0])  # print(arr[0][0][0])

1


In [14]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Slicing

## 1차원 배열의 slicing

In [15]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr[1:5]

array([1, 2, 3, 4])

In [17]:
arr[:3]  # 시작 인덱스 0은 생략 가능

array([0, 1, 2])

In [18]:
arr[-3:]  # 배열의 끝까지 자를 때는 마지막 인덱스를 생략할 수 있음.

array([7, 8, 9])

In [19]:
print(arr[0:1])  #> slicing --> 배열
print(arr[0])    #> indexing --> 배열의 원소

[0]
0


## 2차원 배열의 slicing

In [20]:
arr = np.arange(20).reshape((4, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
print(arr[:2, :])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
print(arr[:2, :3])

[[0 1 2]
 [5 6 7]]


In [24]:
print(arr[1:3, 1:4])

[[ 6  7  8]
 [11 12 13]]


## 3차원 배열의 slicing

In [25]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [26]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [27]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [28]:
print(arr[:2, :2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [29]:
print(arr[:2, :2, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [30]:
print(arr[:2, :2, :2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [31]:
print(arr[:1, :2, :2])  #> 3차원 배열

[[[0 1]
  [5 6]]]


In [32]:
print(arr[0, :2, :2])  #> 2차원 배열

[[0 1]
 [5 6]]
