<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

In [2]:
# Colab의 numpy 버전
np.__version__

'2.0.2'

# `numpy.ndarray` 클래스의 속성들(properties)

In [3]:
# 1차원 배열
arr = np.arange(10)
print(arr)
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (10,)
size: 10
ndim: 1
dtype: int64


In [5]:
# 2차원 배열
arr = np.ones(shape=(2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (2, 3)
size: 6
ndim: 2
dtype: float64


In [9]:
# 3차원 배열(2차원 배열들을 원소로 갖는 배열)
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(arr[0, 0])  # print(arr[0][0])

[1 2 3 4]


In [13]:
print(arr[0, 0, 0])  # print(arr[0][0][0])

1


In [14]:
print('shape:', arr.shape)  #> tuple
print('size:', arr.size)  #> 배열의 모든 아이템의 개수.
print('ndim:', arr.ndim)  #> dimension(차원) - 축(axis)의 개수.
print('dtype:', arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Slicing

## 1차원 배열의 slicing

In [15]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr[1:5]

array([1, 2, 3, 4])

In [17]:
arr[:3]  # 시작 인덱스 0은 생략 가능

array([0, 1, 2])

In [18]:
arr[-3:]  # 배열의 끝까지 자를 때는 마지막 인덱스를 생략할 수 있음.

array([7, 8, 9])

In [19]:
print(arr[0:1])  #> slicing --> 배열
print(arr[0])    #> indexing --> 배열의 원소

[0]
0


## 2차원 배열의 slicing

In [20]:
arr = np.arange(20).reshape((4, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
print(arr[:2, :])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
print(arr[:2, :3])

[[0 1 2]
 [5 6 7]]


In [24]:
print(arr[1:3, 1:4])

[[ 6  7  8]
 [11 12 13]]


## 3차원 배열의 slicing

In [25]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [26]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [27]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [28]:
print(arr[:2, :2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [29]:
print(arr[:2, :2, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [30]:
print(arr[:2, :2, :2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [31]:
print(arr[:1, :2, :2])  #> 3차원 배열

[[[0 1]
  [5 6]]]


In [32]:
print(arr[0, :2, :2])  #> 2차원 배열

[[0 1]
 [5 6]]


# 배열 모양(shape) 변경

*   `reshape()`
*   `ravel()`
*   `flatten()`
*   `numpy.newaxis` 속성

## reshape

In [33]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [34]:
# arr_1d 1차원 배열을 (4, 3) shape의 2차원 배열로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [35]:
# reshape 메서드에서 shape 아규먼트를 전달할 때, 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
arr_2d = arr_1d.reshape((-1, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
arr_1d = np.arange(24)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [38]:
# arr_1d를 (2, 3, 4) shape의 3차원 배열로 변환
arr_3d = arr_1d.reshape((2, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
arr_3d = arr_1d.reshape((2, 3, -1))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
arr_3d = arr_1d.reshape((-1, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## ravel vs flatten

*   ravel
    *   n차원 배열을 1차원 배열로 변환한 **뷰(view)** 를 반환.
    *   새로운 1차원 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원처럼 보여줄 뿐.
    *   반환된 1차원 배열에서 원소를 변경하면, 원본 배열의 원소도 변경됨!
*   flatten
    *   n차원 배열을 1차원 배열로 변환한 **복사본(copy)** 을 반환.
    *   원본 배열과는 별개의 새로운 1차원 배열을 메모리에 생성하고 반환.
    *   반환된 1차원 배열의 원소를 변경해도 원본 배열에는 아무 영향이 없음!

In [41]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
flattened = arr_2d.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
flattened[0] = 123  # 1차원 배열의 첫번째 원소를 123으로 변경
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [47]:
print(arr_2d)  #> flatten() 결과 배열을 수정하는 것은 원본 배열과는 아무런 상관이 없음.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
raveled[0] = 123
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [50]:
print(arr_2d)  #> ravel() 결과 배열을 수정하면 원본이 바뀜.

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [52]:
arr_2d[0, 1] = 345
print(arr_2d)

[[123 345   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [53]:
print(raveled)

[123 345   2   3   4   5   6   7   8   9  10  11]


## `numpy.newaxis` 속성을 사용한 차원 늘리기

In [54]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [55]:
arr.shape  #> (6,) shape - 1d arrary

(6,)

In [56]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4 5]]


In [57]:
result.shape  #> (1, 6) shape - 2d array

(1, 6)

In [60]:
arr.reshape((1, 6))

array([[0, 1, 2, 3, 4, 5]])

In [62]:
arr.reshape((-1, 6))

array([[0, 1, 2, 3, 4, 5]])

In [58]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [59]:
result.shape  # (6, 1) shape - 2d array

(6, 1)

In [64]:
arr.reshape((6, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [66]:
arr.reshape((6, -1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# 배열 합치기(concatenate)

*   `numpy.concatenate()`, `numpy.concat()`: 특정 축(axis) 방향으로 배열을 이어붙이기.
*   `numpy.r_[array1, array2]`: 행(row)들을 이어붙이기. axis=0 방향으로 이어붙이기.
*   `numpy.c_[array1, array2]`: 열(column)들을 이어붙이기. axis=1 방향으로 이어붙이기.

In [67]:
# (2, 3) shape의 2d array
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [68]:
# (1, 3) shape의 2d array
arr2 = np.array([[10, 20, 30]])
print(arr2)

[[10 20 30]]


In [69]:
# (2, 1) shape의 2d array
arr3 = np.array([[100], [200]])
print(arr3)

[[100]
 [200]]


In [71]:
result = np.concat([arr1, arr2])  # axis 파라미터의 기본값은 0.
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


In [72]:
result = np.concat((arr1, arr3), axis=1)
print(result)

[[  0   1   2 100]
 [  3   4   5 200]]


In [73]:
np.r_[arr1, arr2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [74]:
np.c_[arr1, arr3]

array([[  0,   1,   2, 100],
       [  3,   4,   5, 200]])

# Broadcasting

*   `numpy.ndarray`의 연산(`+, -, *, /, ==, !=, >, <, ...`)은 같은 인덱스(위치)의 원소들끼리(element-wise) 연산이 수행됨.
*   서로 모양(shape)이 다른 배열들 사이에서도 element-wise 연산이 가능한 경우가 있음.
*   broadcasting가 가능한 경우:
    *   누락되었거나 길이가 1인 차원에 대해서는 broadcasting이 가능.
    *   이어지는 차원의 축의 길이가 같은 경우에 broadcasting이 가능.

## numpy.ndarray와 scalar(값)의 연산

항상 연산이 가능(항상 broadcating이 가능).

스칼라를 배열의 각 원소마다 연산을 수행.

In [78]:
arr = np.arange(1, 4)
print(arr)
print(arr + 10)
print(arr == 1)

[1 2 3]
[11 12 13]
[ True False False]


In [79]:
arr = np.arange(6).reshape((2, 3))
print(arr)
print(arr + 10)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
