<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANN(Artificial Neural Network, 인공 신경망)

# Imports

In [1]:
from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

In [2]:
# tensorflow 버전
tf.__version__

'2.20.0'

In [3]:
# keras 버전
keras.__version__

'3.13.2'

# Iris 데이터셋

In [4]:
data, target = datasets.load_iris(return_X_y=True)

In [6]:
data.shape  #> (n_samples, n_features)

(150, 4)

In [8]:
target.shape  #> (n_samples,)

(150,)

# 이진 분류(binary classification)

*   2개의 특성만을 사용
*   0(setosa)과 0이 아닌(1-versicolor, 2-virginica) 클래스로 분류

In [9]:
x = data[:, :2]

In [10]:
x.shape

(150, 2)

In [11]:
x[:5]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [14]:
y = (target != 0).astype('int')

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# SGD Classifier(확률적 경사 하강법 분류기)

In [16]:
# loss='log_loss': logistic 손실 함수를 최소화하는 확률적 경사 하강법을 사용하기 위해서.
# sigmoid 함수로 클래스 0이 될 확률과 클래스 1이 될 확률을 계산하기 위해서
# max_iter=10: epoch 횟수를 10번으로 제한.
# epoch: 모든 샘플을 1번 사용해서 경사하강법을 수행.
sgd = SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [17]:
# 모델 훈련 -> 손실함수를 최소화하는 가중치(coefficients, intercepts)들을 찾는 과정.
sgd.fit(X=x, y=y)

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [18]:
sgd.coef_  #> (1, 2) shape의 2차원 배열

array([[ 107.47482122, -163.79917975]])

In [19]:
sgd.intercept_  #> (1,) shape의 1차원 배열

array([-53.41269101])

$z = -53.4 + 107.4 \times x_1 - 163.7 \times x_2$

In [20]:
# SGD 모델의 예측값
y_pred = sgd.predict(X=x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
# SGD 모델의 정확도
accuracy_score(y_true=y, y_pred=y_pred)

0.9933333333333333

In [22]:
149/150

0.9933333333333333

In [23]:
# SGD 모델이 계산한 예측 확률
pred_prob = sgd.predict_proba(X=x)

In [25]:
pred_prob.shape

(150, 2)

In [26]:
pred_prob[:5]

array([[1.00000000e+00, 7.40567283e-35],
       [9.99999987e-01, 1.26753544e-08],
       [1.00000000e+00, 3.47056174e-32],
       [1.00000000e+00, 9.69472704e-30],
       [1.00000000e+00, 1.22541827e-46]])

In [27]:
pred_prob[-5:]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [28]:
pred_prob[y != y_pred]

array([[0., 1.]])

# 신경망(Neural Network)

In [29]:
# 입력층(input layer)
inputs = keras.Input(shape=(2,))

In [30]:
# 출력층(output layer)
dense = keras.layers.Dense(units=1, activation='sigmoid')

In [31]:
# 신경망 모델 생성
model = keras.Sequential(layers=[inputs, dense])

In [32]:
# 생성된 신경망 모델 정보 요약
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
# 신경망 모델 컴파일: optimizer(최적화 알고리즘), loss(손실 함수), metrics(평가 기준)을 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [34]:
# 신경망 모델 훈련
model.fit(x=x, y=y, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - binary_accuracy: 0.3333 - loss: 5.2625  
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.3333 - loss: 4.2015 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.3333 - loss: 3.1434 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.3333 - loss: 2.1536 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - binary_accuracy: 0.3333 - loss: 1.3159
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - binary_accuracy: 0.3533 - loss: 0.7967
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.7867 - loss: 0.5760 
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.9867 - loss: 0.5023
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - binary_accuracy: 0.8800 - loss: 0.4750
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.8200 - loss: 0.4664


In [35]:
# 신경망 모델이 학습을 통해서 찾은 모델 파라미터들(weights, 가중치)
model.weights

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[ 0.42823157]
  [-0.65887463]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[0.19072565]>]

$z = 0.19 + 0.42 \times x_1 - 0.65 \times x_2$

In [36]:
# 학습이 끝난 신경망 모델의 예측값 계산
y_pred = model.predict(x=x)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


In [38]:
y_pred.shape

(150, 1)

In [39]:
y_pred[:5]

array([[0.5171546 ],
       [0.5774799 ],
       [0.52373594],
       [0.52948564],
       [0.48998505]], dtype=float32)

In [40]:
y_pred[-5:]

array([[0.7471091 ],
       [0.7758073 ],
       [0.73058784],
       [0.6469336 ],
       [0.67714196]], dtype=float32)

In [41]:
y_pred_label = (y_pred >= 0.5).astype('int').ravel()
y_pred_label

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
# 정확도
accuracy_score(y_true=y, y_pred=y_pred_label)

0.76

In [43]:
model.evaluate(x=x, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7600 - loss: 0.4614  


[0.4613635241985321, 0.7599999904632568]

# 은닉층(hidden layer)을 갖는 신경망

In [44]:
inputs = keras.layers.Input(shape=(2,))  # 입력층(input layer)
dense1 = keras.layers.Dense(units=2, activation='sigmoid')  # 은닉층(hidden layer)
dense2 = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층(output layer)

In [45]:
# 신경망 모델 생성
model = keras.Sequential(layers=[inputs, dense1, dense2])

In [46]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
# 신경망 모델 컴파일
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [48]:
# 신경망 모델 훈련
model.fit(x=x, y=y, batch_size=10, epochs=10)

Epoch 1/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.4667 - loss: 0.6769  
Epoch 2/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8467 - loss: 0.6717 
Epoch 3/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9867 - loss: 0.6668 
Epoch 4/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 1.0000 - loss: 0.6622 
Epoch 5/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9667 - loss: 0.6577 
Epoch 6/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9600 - loss: 0.6533 
Epoch 7/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8933 - loss: 0.6492 
Epoch 8/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8667 - loss: 0.6449 
Epoch 9/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8333 - loss: 0.6409 
Epoch 10/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8267 - loss: 0.6369 


In [49]:
# 훈련이 끝난 신경망이 찾은 가중치들
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(2, 2), dtype=float32, value=[[-0.951283   -1.063439  ]
  [ 0.80386966  1.0331359 ]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(2,), dtype=float32, value=[0.00494676 0.01680949]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(2, 1), dtype=float32, value=[[-0.4262791]
  [-1.164876 ]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(1,), dtype=float32, value=[0.23496425]>]

In [50]:
model.evaluate(x=x, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8200 - loss: 0.6346  


[0.634643018245697, 0.8199999928474426]