<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml18_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CNN(Convolutional Neural Network, 합성곱 신경망)

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.signal import convolve, convolve2d, correlate, correlate2d
from sklearn.datasets import load_sample_image, load_sample_images
from sklearn.metrics import confusion_matrix

import keras

# 1차원 배열 합성곱 연산(1D Convolution)

In [2]:
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [3]:
y = np.array([1, 2])
print(y)

[1 2]


In [4]:
y_flip = np.flip(y)
print(y_flip)

[2 1]


## `convolve()` 함수

scipy 패키지의 convolve 함수는 배열 y를 반전(flip)시키고 합성곱 연산을 수행.

In [5]:
# 'valid' 모드: 결과가 배열 x보다 크기가 줄어듦.
result = convolve(x, y, mode='valid')
print(result)

[ 4  7 10]


In [6]:
# 'same' 모드: 결과가 배열 x의 크기와 같음.
result = convolve(x, y, mode='same')
print(result)

[ 1  4  7 10]


In [7]:
# 'full' 모드: 배열 x의 모든 원소들이 합성곱 연산에서 같은 비율(횟수)로 참여하도록 패딩을 넣고 연산을 수행.
result = convolve(x, y, mode='full')
print(result)

[ 1  4  7 10  8]


## `correlate()` 함수

교차상관(cross-corrleate): 배열 y를 반전시키지 않고 합성곱 연산을 수행.

In [8]:
result = correlate(x, y, mode='valid')
print(result)

[ 5  8 11]


In [9]:
result = correlate(x, y, mode='same')
print(result)

[ 2  5  8 11]


In [10]:
result = correlate(x, y, mode='full')
print(result)

[ 2  5  8 11  4]


# 2차원 배열 합성곱(2D Convolution)