<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml22_llm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EXAONE 모델을 사용한 질문-답변 시스템

In [8]:
# EXAONE 모델을 transformers.pipeline()으로 사용하기 위해서(에러 제거)
!pip install transformers==5.1.0

# Imports

In [1]:
import numpy as np
import scipy
import transformers

In [2]:
transformers.__version__  #> 5.1.0

'5.1.0'

In [3]:
# transformers 모듈의 함수를 사용할 때 progress bar를 출력창에 보여주는 것을 비활성.
transformers.utils.logging.disable_progress_bar()

# EXAONE-3.5 모델

In [4]:
pipe = transformers.pipeline(
    task='text-generation',
    model='LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct',
    device=0,  # GPU 사용
    trust_remote_code=True
)

In [5]:
# 메시지 템플릿: 'role'과 'content'를 키로 갖는 dict들의 list.
# role: 역할(system, user, assistant)
# content: 내용
messages = [
    {
        'role': 'system',
        'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'
    },
    {
        'role': 'user',
        'content': '2026 아시안게임 야구 우승팀은 어느 나라야?',
    }
]

In [18]:
result = pipe(messages, max_new_tokens=200)

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


In [19]:
print(result)

[{'generated_text': [{'role': 'system', 'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'}, {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'}, {'role': 'assistant', 'content': '2026년 아시안 게임의 야구 대회에 대한 구체적인 우승 예측은 현재로서는 확실하지 않습니다. 스포츠 이벤트의 결과는 여러 변수에 따라 달라질 수 있으며, 이는 팀들의 최근 성적, 선수들의 상태, 전략적 준비 상태 등에 크게 의존합니다.\n\n정확한 정보를 얻으시려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안게임 웹사이트**: 최신 정보와 관련 소식을 확인할 수 있습니다.\n2. **스포츠 뉴스 매체**: ESPN 아시아, SBS 스포츠 등 신뢰할 수 있는 스포츠 뉴스 플랫폼을 통해 업데이트를 찾아보세요.\n3. **팀별 공식 발표**: 각 참가 국가의 야구 연맹이나 팀들이 공식적으로 발표하는 정보를 참고하세요.\n\n이러한 출처들을 통해 가장 최신의 예측과 정보를 얻으실 수 있을 것입니다.'}]}]


In [20]:
print(type(result))

<class 'list'>


In [21]:
len(result)
#> pipeline이 리턴하는 값은 아이템이 1개인 list.

1

In [22]:
result[0]  #> dict

{'generated_text': [{'role': 'system',
   'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'},
  {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'},
  {'role': 'assistant',
   'content': '2026년 아시안 게임의 야구 대회에 대한 구체적인 우승 예측은 현재로서는 확실하지 않습니다. 스포츠 이벤트의 결과는 여러 변수에 따라 달라질 수 있으며, 이는 팀들의 최근 성적, 선수들의 상태, 전략적 준비 상태 등에 크게 의존합니다.\n\n정확한 정보를 얻으시려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안게임 웹사이트**: 최신 정보와 관련 소식을 확인할 수 있습니다.\n2. **스포츠 뉴스 매체**: ESPN 아시아, SBS 스포츠 등 신뢰할 수 있는 스포츠 뉴스 플랫폼을 통해 업데이트를 찾아보세요.\n3. **팀별 공식 발표**: 각 참가 국가의 야구 연맹이나 팀들이 공식적으로 발표하는 정보를 참고하세요.\n\n이러한 출처들을 통해 가장 최신의 예측과 정보를 얻으실 수 있을 것입니다.'}]}

In [23]:
result[0].keys()

dict_keys(['generated_text'])

In [24]:
result[0].get('generated_text')  #> dict의 값(value)은 list

[{'role': 'system', 'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'},
 {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'},
 {'role': 'assistant',
  'content': '2026년 아시안 게임의 야구 대회에 대한 구체적인 우승 예측은 현재로서는 확실하지 않습니다. 스포츠 이벤트의 결과는 여러 변수에 따라 달라질 수 있으며, 이는 팀들의 최근 성적, 선수들의 상태, 전략적 준비 상태 등에 크게 의존합니다.\n\n정확한 정보를 얻으시려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안게임 웹사이트**: 최신 정보와 관련 소식을 확인할 수 있습니다.\n2. **스포츠 뉴스 매체**: ESPN 아시아, SBS 스포츠 등 신뢰할 수 있는 스포츠 뉴스 플랫폼을 통해 업데이트를 찾아보세요.\n3. **팀별 공식 발표**: 각 참가 국가의 야구 연맹이나 팀들이 공식적으로 발표하는 정보를 참고하세요.\n\n이러한 출처들을 통해 가장 최신의 예측과 정보를 얻으실 수 있을 것입니다.'}]

In [25]:
result[0].get('generated_text')[-1].get('content')

'2026년 아시안 게임의 야구 대회에 대한 구체적인 우승 예측은 현재로서는 확실하지 않습니다. 스포츠 이벤트의 결과는 여러 변수에 따라 달라질 수 있으며, 이는 팀들의 최근 성적, 선수들의 상태, 전략적 준비 상태 등에 크게 의존합니다.\n\n정확한 정보를 얻으시려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안게임 웹사이트**: 최신 정보와 관련 소식을 확인할 수 있습니다.\n2. **스포츠 뉴스 매체**: ESPN 아시아, SBS 스포츠 등 신뢰할 수 있는 스포츠 뉴스 플랫폼을 통해 업데이트를 찾아보세요.\n3. **팀별 공식 발표**: 각 참가 국가의 야구 연맹이나 팀들이 공식적으로 발표하는 정보를 참고하세요.\n\n이러한 출처들을 통해 가장 최신의 예측과 정보를 얻으실 수 있을 것입니다.'

In [26]:
print(result[0].get('generated_text')[-1].get('content'))

2026년 아시안 게임의 야구 대회에 대한 구체적인 우승 예측은 현재로서는 확실하지 않습니다. 스포츠 이벤트의 결과는 여러 변수에 따라 달라질 수 있으며, 이는 팀들의 최근 성적, 선수들의 상태, 전략적 준비 상태 등에 크게 의존합니다.

정확한 정보를 얻으시려면 다음과 같은 방법을 추천드립니다:
1. **공식 아시안게임 웹사이트**: 최신 정보와 관련 소식을 확인할 수 있습니다.
2. **스포츠 뉴스 매체**: ESPN 아시아, SBS 스포츠 등 신뢰할 수 있는 스포츠 뉴스 플랫폼을 통해 업데이트를 찾아보세요.
3. **팀별 공식 발표**: 각 참가 국가의 야구 연맹이나 팀들이 공식적으로 발표하는 정보를 참고하세요.

이러한 출처들을 통해 가장 최신의 예측과 정보를 얻으실 수 있을 것입니다.


pipeline 객체는 실행할 때마다 다른 답변(텍스트)을 생성함.

pipeline 파라미터:
*   `return_full_text`: 이전의 대화 기록을 모두 리턴할지 여부를 설정. 기본값은 True.
*   `do_sample`: 샘플링 전략을 사용할지 여부를 설정. 기본값은 True.
    *   `do_sample=True`: 메시지 프롬프트가 같아도 실행할 때마다 생성되는 텍스트가 달라짐.
    *   `do_sample=False`
        *   메시지 프롬프트가 같으면 항상 같은 텍스트가 생성됨.
        *   가장 확률이 높은 토큰들을 선택해서 텍스트를 생성하기 때문에.
*   샘플링 전략
    *   temperature
    *   top-k 방식
    *   top-p 방식

In [28]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=False)
print(result)

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '2026년 아시안 게임의 야구 대회에 대한 구체적인 우승팀 정보는 아직 공식적으로 발표되지 않았습니다. 아시안 게임의 야구 대회는 매년 개최국에서 열리며, 참가국과 우승팀은 대회 직전에 결정됩니다. \n\n정확한 정보를 얻으려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안 게임 웹사이트**: 최신 업데이트와 공식 발표를 확인할 수 있습니다.\n2. **스포츠 뉴스 사이트**: 신뢰할 수 있는 스포츠 뉴스 매체에서 최신 소식을 찾아볼 수 있습니다.\n3. **관련 스포츠 커뮤니티**: 팬 커뮤니티나 스포츠 포럼에서도 실시간 정보를 얻을 수 있습니다.\n\n이러한 출처들을 통해 가장 최신의 정보를 얻으실 수 있을 것입니다.'}]


2026년 아시안 게임의 야구 대회에 대한 구체적인 우승팀 정보는 아직 공식적으로 발표되지 않았습니다. 아시안 게임의 야구 대회는 매년 개최국에서 열리며, 참가국과 우승팀은 대회 직전에 결정됩니다. \n\n정확한 정보를 얻으려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안 게임 웹사이트**: 최신 업데이트와 공식 발표를 확인할 수 있습니다.\n2. **스포츠 뉴스 사이트**: 신뢰할 수 있는 스포츠 뉴스 매체에서 최신 소식을 찾아볼 수 있습니다.\n3. **관련 스포츠 커뮤니티**: 팬 커뮤니티나 스포츠 포럼에서도 실시간 정보를 얻을 수 있습니다.\n\n이러한 출처들을 통해 가장 최신의 정보를 얻으실 수 있을 것입니다.

# temperature 샘플링 전략

temperature(온도)를 1보다 큰 값으로 설정하면 AI가 텍스트를 생성할 때 선택되는 토큰들이 다양해지기 때문에 답변이 매우 무작위적이 됨.

temperature를 1보다 작은 값으로 설정하면 높은 확률을 가진 토큰들이 선택될 가능성이 더 커짐. AI가 생성하는 텍스트(답변)은 더 일관되어 짐.

In [31]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=True,  # 기본값
              temperature=10.0)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


정확한글로나 특정 시간 후 정확 결과 말씀드림직해지만,, 말씀 나누면 실제는 아직 발행 및 정해지안 최종 사항 입니다 만... 지금 정확히 특정 해 이전까지의 예상이나 과거 성과, 과거 결과 들으시지 하시진 않아지 말씀해 주시다니 아시긴하지만, 직접 결정에 앞서 제 대답 가능 범위의 지식 데이터 상의 접근이라 항상 현재 개최 장소 기준 으로 가장 우수 예상이 **국내 (대한민국이기도 합니다 왜냐하면 홈 경기 advantage 로 긍정평가가능^^ 을 제공하니*) 와 참가 국가 별 이전 예선 통과 등의 요소 있어요. 그러므로 국제 컨택 후 확인 보시는 분한도 계시면서도 제일 확정지는  조직화측 공식발굴 시기부터 안내 받드시게 됩니다.' 대한민국의 강력해진 역량 과 꾸준했내 기대' 이라던 맥락이나 예상도 널리 들어보면 이해가 더 됩니다.; 명확예측 어려움 강조드려봅니다._conjecture 와 정보공개 주의 부분_ 에서 제 제공의 기준 에 해당합니다., 최대한


In [33]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=True,  # 기본값
              temperature=0.1)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


2026 아시안게임 야구 대회의 우승팀에 대한 정보는 현재 공식적으로 발표되지 않았습니다. 아시안게임은 매년 개최국에서 열리며, 야구 경기의 경우 참가국들의 성적에 따라 우승팀이 결정됩니다. 정확한 우승팀 정보는 해당 대회가 개최되는 해의 공식 발표나 관련 스포츠 뉴스를 통해 확인하실 수 있습니다. 만약 특정 국가나 최근 동향에 대해 궁금하시다면 좀 더 구체적인 정보를 제공해 주시면 도움을 드릴 수 있을 것 같습니다.


In [38]:
# 동전 던지기
probs = [0.5, 0.5]  # 앞면이 나올 확률, 뒷면이 나올 확률

# 실험
np.random.multinomial(n=100, pvals=probs)

array([48, 52])

In [43]:
# 주사위 던지기 실험
probs = [1/6] * 6  # [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
np.random.multinomial(n=600, pvals=probs)

array([ 92,  95, 100, 112, 106,  95])

logit(로짓): softmax 함수의 아규먼트. LLM에서 어휘 사전에 포함된 각 토큰들의 점수. 점수가 높으면 선택될 확률이 높은 토큰(단어), 점수가 낮으면 선택될 확률이 낮은 토큰.

In [52]:
logits = np.array([1, 2, 3, 4, 10])  # 5개 토큰의 점수.
probs = scipy.special.softmax(logits)
print(probs)

[1.22936559e-04 3.34176214e-04 9.08385131e-04 2.46924679e-03
 9.96165255e-01]


In [56]:
np.random.multinomial(n=500, pvals=probs)

array([  0,   0,   1,   0, 499])

In [59]:
logits_scaled = logits / 10
print('logits_scaled:', logits_scaled)

probs = scipy.special.softmax(logits_scaled)
print('probabilities:', probs)

ex = np.random.multinomial(n=500, pvals=probs)
print('실험 결과:', ex)

logits_scaled: [0.1 0.2 0.3 0.4 1. ]
probabilities: [0.14013383 0.15487183 0.17115985 0.18916088 0.3446736 ]
실험 결과: [ 61  85  98  83 173]


In [60]:
logits_scaled = logits / 0.1
print('logits_scaled:', logits_scaled)

probs = scipy.special.softmax(logits_scaled)
print('probabilities:', probs)

ex = np.random.multinomial(n=500, pvals=probs)
print('실험 결과:', ex)

logits_scaled: [ 10.  20.  30.  40. 100.]
probabilities: [8.19401262e-40 1.80485139e-35 3.97544974e-31 8.75651076e-27
 1.00000000e+00]
실험 결과: [  0   0   0   0 500]



*   LLM에서 온도(temperature)는 logit 값들을 나눠주는 수.
*   logit 값들을 1보다 큰 수로 나눈 후 softmax 함수로 확률을 계산하면, logit 값이 작은 토큰들의 확률이 커지는 효과.
    *   토큰을 선택하는 다양성이 커짐.
    *   생성되는 텍스트가 다양해짐.
*   logit 값을 1보다 작은 수로 나눈 후 softmax 함수로 확률을 계산하면, logit 값이 큰 토큰들의 확률을 더 크게 만드는 효과
    *   토큰을 선택하는 다양성이 작아짐.
    *   거의 비슷한 텍스트들이 생성됨.
