<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml22_llm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EXAONE 모델을 사용한 질문-답변 시스템

In [2]:
# EXAONE 모델을 transformers.pipeline()으로 사용하기 위해서(에러 제거)
!pip install transformers==5.1.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 94.1 MB/s eta 0:00:00
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.23.1
    Uninstalling tokenizers-0.23.1:
      Successfully uninstalled tokenizers-0.23.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.16.1
    Uninstalling transformers-5.16.1:
      Successfully uninstalled transformers-5.16.1


# Imports

In [1]:
import numpy as np
import scipy
import transformers

In [2]:
transformers.__version__  #> 5.1.0

'5.1.0'

In [3]:
# transformers 모듈의 함수를 사용할 때 progress bar를 출력창에 보여주는 것을 비활성.
transformers.utils.logging.disable_progress_bar()

# EXAONE-3.5 모델

In [4]:
pipe = transformers.pipeline(
    task='text-generation',
    model='LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct',
    device=0,  # GPU 사용
    trust_remote_code=True
)

A new version of the following files was downloaded from https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct:
- configuration_exaone.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct:
- modeling_exaone.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


In [5]:
# 메시지 템플릿: 'role'과 'content'를 키로 갖는 dict들의 list.
# role: 역할(system, user, assistant)
# content: 내용
messages = [
    {
        'role': 'system',
        'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'
    },
    {
        'role': 'user',
        'content': '2026 아시안게임 야구 우승팀은 어느 나라야?',
    }
]

In [6]:
result = pipe(messages, max_new_tokens=200)

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


In [7]:
print(result)

[{'generated_text': [{'role': 'system', 'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'}, {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'}, {'role': 'assistant', 'content': '죄송합니다, 하지만 현재 시점에서 정확한 2026 아시안게임 야구 우승팀을 예측하거나 확정적으로 말씀드리기는 어렵습니다. 아시안게임의 개최 일정은 아직 확정되지 않았으며, 팀들의 성적은 게임 진행 상황에 따라 변동될 수 있습니다.\n\n2026년 아시안게임이 실제 개최될 경우, 주요 참가국들로는 일본, 한국, 중국, 태국 등이 예상되지만, 실제로 어떤 팀이 우승할지는 그 해의 경기 결과에 따라 결정될 것입니다. 최신 정보나 공식 발표를 확인하시려면 해당 이벤트의 공식 웹사이트나 관련 스포츠 뉴스를 참고하시는 것이 가장 정확할 것입니다.'}]}]


In [8]:
print(type(result))

<class 'list'>


In [9]:
len(result)
#> pipeline이 리턴하는 값은 아이템이 1개인 list.

1

In [10]:
result[0]  #> dict

{'generated_text': [{'role': 'system',
   'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'},
  {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'},
  {'role': 'assistant',
   'content': '죄송합니다, 하지만 현재 시점에서 정확한 2026 아시안게임 야구 우승팀을 예측하거나 확정적으로 말씀드리기는 어렵습니다. 아시안게임의 개최 일정은 아직 확정되지 않았으며, 팀들의 성적은 게임 진행 상황에 따라 변동될 수 있습니다.\n\n2026년 아시안게임이 실제 개최될 경우, 주요 참가국들로는 일본, 한국, 중국, 태국 등이 예상되지만, 실제로 어떤 팀이 우승할지는 그 해의 경기 결과에 따라 결정될 것입니다. 최신 정보나 공식 발표를 확인하시려면 해당 이벤트의 공식 웹사이트나 관련 스포츠 뉴스를 참고하시는 것이 가장 정확할 것입니다.'}]}

In [11]:
result[0].keys()

dict_keys(['generated_text'])

In [12]:
result[0].get('generated_text')  #> dict의 값(value)은 list

[{'role': 'system', 'content': '너는 사용자의 질문에 정확한 답변을 해주는 친절한 AI 비서야.'},
 {'role': 'user', 'content': '2026 아시안게임 야구 우승팀은 어느 나라야?'},
 {'role': 'assistant',
  'content': '죄송합니다, 하지만 현재 시점에서 정확한 2026 아시안게임 야구 우승팀을 예측하거나 확정적으로 말씀드리기는 어렵습니다. 아시안게임의 개최 일정은 아직 확정되지 않았으며, 팀들의 성적은 게임 진행 상황에 따라 변동될 수 있습니다.\n\n2026년 아시안게임이 실제 개최될 경우, 주요 참가국들로는 일본, 한국, 중국, 태국 등이 예상되지만, 실제로 어떤 팀이 우승할지는 그 해의 경기 결과에 따라 결정될 것입니다. 최신 정보나 공식 발표를 확인하시려면 해당 이벤트의 공식 웹사이트나 관련 스포츠 뉴스를 참고하시는 것이 가장 정확할 것입니다.'}]

In [13]:
result[0].get('generated_text')[-1].get('content')

'죄송합니다, 하지만 현재 시점에서 정확한 2026 아시안게임 야구 우승팀을 예측하거나 확정적으로 말씀드리기는 어렵습니다. 아시안게임의 개최 일정은 아직 확정되지 않았으며, 팀들의 성적은 게임 진행 상황에 따라 변동될 수 있습니다.\n\n2026년 아시안게임이 실제 개최될 경우, 주요 참가국들로는 일본, 한국, 중국, 태국 등이 예상되지만, 실제로 어떤 팀이 우승할지는 그 해의 경기 결과에 따라 결정될 것입니다. 최신 정보나 공식 발표를 확인하시려면 해당 이벤트의 공식 웹사이트나 관련 스포츠 뉴스를 참고하시는 것이 가장 정확할 것입니다.'

In [14]:
print(result[0].get('generated_text')[-1].get('content'))

죄송합니다, 하지만 현재 시점에서 정확한 2026 아시안게임 야구 우승팀을 예측하거나 확정적으로 말씀드리기는 어렵습니다. 아시안게임의 개최 일정은 아직 확정되지 않았으며, 팀들의 성적은 게임 진행 상황에 따라 변동될 수 있습니다.

2026년 아시안게임이 실제 개최될 경우, 주요 참가국들로는 일본, 한국, 중국, 태국 등이 예상되지만, 실제로 어떤 팀이 우승할지는 그 해의 경기 결과에 따라 결정될 것입니다. 최신 정보나 공식 발표를 확인하시려면 해당 이벤트의 공식 웹사이트나 관련 스포츠 뉴스를 참고하시는 것이 가장 정확할 것입니다.


pipeline 객체는 실행할 때마다 다른 답변(텍스트)을 생성함.

pipeline 파라미터:
*   `return_full_text`: 이전의 대화 기록을 모두 리턴할지 여부를 설정. 기본값은 True.
*   `do_sample`: 샘플링 전략을 사용할지 여부를 설정. 기본값은 True.
    *   `do_sample=True`: 메시지 프롬프트가 같아도 실행할 때마다 생성되는 텍스트가 달라짐.
    *   `do_sample=False`
        *   메시지 프롬프트가 같으면 항상 같은 텍스트가 생성됨.
        *   가장 확률이 높은 토큰들을 선택해서 텍스트를 생성하기 때문에.
*   샘플링 전략
    *   temperature
    *   top-k 방식
    *   top-p 방식

In [15]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=False)
print(result)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '2026년 아시안 게임의 야구 대회에 대한 구체적인 우승팀 정보는 아직 공식적으로 발표되지 않았습니다. 아시안 게임의 야구 대회는 매년 개최국에서 열리며, 참가국과 우승팀은 대회 직전에 결정됩니다. \n\n정확한 정보를 얻으려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안 게임 웹사이트**: 최신 업데이트와 공식 발표를 확인할 수 있습니다.\n2. **스포츠 뉴스 사이트**: 신뢰할 수 있는 스포츠 뉴스 매체에서 최신 소식을 찾아볼 수 있습니다.\n3. **관련 스포츠 커뮤니티**: 팬 커뮤니티나 스포츠 포럼에서도 실시간 정보를 얻을 수 있습니다.\n\n이러한 출처들을 통해 가장 최신의 정보를 얻으실 수 있을 것입니다.'}]


2026년 아시안 게임의 야구 대회에 대한 구체적인 우승팀 정보는 아직 공식적으로 발표되지 않았습니다. 아시안 게임의 야구 대회는 매년 개최국에서 열리며, 참가국과 우승팀은 대회 직전에 결정됩니다. \n\n정확한 정보를 얻으려면 다음과 같은 방법을 추천드립니다:\n1. **공식 아시안 게임 웹사이트**: 최신 업데이트와 공식 발표를 확인할 수 있습니다.\n2. **스포츠 뉴스 사이트**: 신뢰할 수 있는 스포츠 뉴스 매체에서 최신 소식을 찾아볼 수 있습니다.\n3. **관련 스포츠 커뮤니티**: 팬 커뮤니티나 스포츠 포럼에서도 실시간 정보를 얻을 수 있습니다.\n\n이러한 출처들을 통해 가장 최신의 정보를 얻으실 수 있을 것입니다.

# temperature 샘플링 전략

temperature(온도)를 1보다 큰 값으로 설정하면 AI가 텍스트를 생성할 때 선택되는 토큰들이 다양해지기 때문에 답변이 매우 무작위적이 됨.

temperature를 1보다 작은 값으로 설정하면 높은 확률을 가진 토큰들이 선택될 가능성이 더 커짐. AI가 생성하는 텍스트(답변)은 더 일관되어 짐.

In [16]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=True,  # 기본값
              temperature=10.0)
print(result[0].get('generated_text'))

Passing `generation_config` together with generation-related arguments=({'temperature', 'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


 제게는 그런실시간 올림픽 티켓으로 확인하기 어려운 업데이트 기반 데이터 또는 예상을 실시간 업데이트에 제공합니다._siggest로 인한 불활성적이나 직접적 사건 관련 결정에 의존은 정확하기 어려워질 수입집니다 그러나 실제 계획 수립 당시에 대해 알 수 못한다면 공식 [유효 시점 기준이 필요], 따라서 **자세항 계획 예측 불가능으로 직접 승리는 경기 진행 예정과 정확 데이터 따라** 변경 사항 여부 필요할게요। 과거 패턴과 경쟁 국 들 동향 등의 요인으로 추리된 어떤 팀 예상이 많이 퍼져 왔으나 최후 선택을 통한 답변드리는지 못합니다— 정확 답 제공드리도록 늘 개선될 의지로 임하자던 [아시아 중앙 방송 올림픽 축구와 배구 예선] 같은행력 팀들이 참여하여 어떤 특정 기간 결정 여부, 가장 신뢰할 수 데이터 최신이 요구 받았나이정이 정확히 적용 시 예측할게요 : **_K League_** 한국과, **.Portsmaer Baseball International Games에서 지난 성공 사례 여러 국제 경기장 또는 개최국들이


In [17]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              do_sample=True,  # 기본값
              temperature=0.1)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


2026 아시안게임 야구 대회의 우승팀에 대한 정보는 아직 공식적으로 발표되지 않았습니다. 아시안게임은 매년 개최국에서 열리며, 야구 경기의 경우 참가국들의 성적에 따라 우승팀이 결정됩니다. 정확한 우승팀 정보는 해당 대회가 개최되는 해의 공식 발표나 관련 스포츠 뉴스를 통해 확인하실 수 있습니다. 만약 특정 국가에 대한 관심이 있으시다면, 그 국가의 야구 팀 동향이나 최근 성적을 참고하시는 것도 도움이 될 수 있습니다. 최신 정보를 원하신다면, 가까운 시일 내에 업데이트된 공식 출처를 확인해 보시는 것이 좋습니다.


In [18]:
# 동전 던지기
probs = [0.5, 0.5]  # 앞면이 나올 확률, 뒷면이 나올 확률

# 실험
np.random.multinomial(n=100, pvals=probs)

array([60, 40])

In [19]:
# 주사위 던지기 실험
probs = [1/6] * 6  # [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
np.random.multinomial(n=600, pvals=probs)

array([ 96,  96, 108,  94,  94, 112])

logit(로짓): softmax 함수의 아규먼트. LLM에서 어휘 사전에 포함된 각 토큰들의 점수. 점수가 높으면 선택될 확률이 높은 토큰(단어), 점수가 낮으면 선택될 확률이 낮은 토큰.

In [20]:
logits = np.array([1, 2, 3, 4, 10])  # 5개 토큰의 점수.
probs = scipy.special.softmax(logits)
print(probs)

[1.22936559e-04 3.34176214e-04 9.08385131e-04 2.46924679e-03
 9.96165255e-01]


In [21]:
np.random.multinomial(n=500, pvals=probs)

array([  0,   0,   0,   1, 499])

In [22]:
logits_scaled = logits / 10
print('logits_scaled:', logits_scaled)

probs = scipy.special.softmax(logits_scaled)
print('probabilities:', probs)

ex = np.random.multinomial(n=500, pvals=probs)
print('실험 결과:', ex)

logits_scaled: [0.1 0.2 0.3 0.4 1. ]
probabilities: [0.14013383 0.15487183 0.17115985 0.18916088 0.3446736 ]
실험 결과: [ 71  75  86  85 183]


In [23]:
logits_scaled = logits / 0.1
print('logits_scaled:', logits_scaled)

probs = scipy.special.softmax(logits_scaled)
print('probabilities:', probs)

ex = np.random.multinomial(n=500, pvals=probs)
print('실험 결과:', ex)

logits_scaled: [ 10.  20.  30.  40. 100.]
probabilities: [8.19401262e-40 1.80485139e-35 3.97544974e-31 8.75651076e-27
 1.00000000e+00]
실험 결과: [  0   0   0   0 500]



*   LLM에서 온도(temperature)는 logit 값들을 나눠주는 수.
*   logit 값들을 1보다 큰 수로 나눈 후 softmax 함수로 확률을 계산하면, logit 값이 작은 토큰들의 확률이 커지는 효과.
    *   토큰을 선택하는 다양성이 커짐.
    *   생성되는 텍스트가 다양해짐.
*   logit 값을 1보다 작은 수로 나눈 후 softmax 함수로 확률을 계산하면, logit 값이 큰 토큰들의 확률을 더 크게 만드는 효과
    *   토큰을 선택하는 다양성이 작아짐.
    *   거의 비슷한 텍스트들이 생성됨.


# top-k 샘플링

모델이 계산한 토큰들의 logit(점수) 값들을 정렬해서 최상위 k개의 토큰 들 중에 선택하는 샘플링 방식.

k값이 클 수록 더 다양한 텍스트들이 생성될 수 있음.

k값이 작을 수록 일관된 텍스트들이 생성됨.

In [26]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              temperature=1.5,
              top_k=100)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


2026년 아시안 게임의 정식 개최국 발표가 아직 이루어지지 않았으며, consequently 예측이나 명확한 결론을 내리기는 어렵습니다. 일반적으로 이 대회에서 우승 국가는 주로 강점을 가진 메이저 스포츠 강국이나 아시아 야구 강국들이 유력한 contender입니다. 

이전 대회 결과를 보면:
- **2018 자카르타·팔렘방 아시안게임** 결과 대한민국이 우승하였습니다.

추후 발표가 될 정확한 개최지와 참가 팀 업데이트에 대해서는 공식 웹사이트나 관련 국제기구의 공지사항을 확인해 보시는 것이 가장 정확할 것입니다. 만약 특정한 개최지나 추가적인 정보가 필요하시다면 알려주세요!


In [28]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              temperature=1.5,
              top_k=10)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


죄송합니다만, 현재시점에서 구체적인 개최국이나 대회 결과에 대한 실시간 또는 정확한 정보를 제공하기는 어렵습니다. 2026년 아시안게임의 정확한 일정과 결과는 국제 스포츠 연맹(예: FIFA 국제 축구 평의회나 대한야구위원회 등)과 공식 웹사이트에서 최신으로 확인하실 수 있습니다. 예정되어 있는 날짜나 결과에 대한 업데이트를 통해 우승팀에 대해 알 수 있을 것입니다. 관련 정보가 업데이트된 곳을 확인해 보시는 게 가장 정확할 것 같습니다.


# top-p 샘플링

모델이 출력한 logit 값으로 계산한 확률 크기 순서로 (내림차순) 정렬했을 때, 누적 확률 p까지의 토큰을 샘플링하는 방법.

top_p(누적 확률) 값이 클 수록 다양한 텍스트가 생성되고, 작을 수록 일관된 텍스트들이 생성됨.

누적 확률 p가 동일하더라도 선택될 수 있는 토큰의 개수는 달라질 수 있음.

top-p 샘플링 방식은 다양한 확률 분포에 유연하게 대처할 수 있음.

top-k 샘플링 방식은 선택하는 토큰들의 개수를 고정시키기 때문에 높은 확률을 가진 토큰이 선택에서 제외될 수 있음.

In [31]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              temperature=1.5,
              top_p=0.9)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


2026년아시아게임 야구 대회의 정확한 우승 국가는 아직 공식 발표되지 않았습니다. 아시아올림픽평의회(OCA)는대회 일정과 참가국 명단 등에 대한 정보를 발표하고 있으나, 정확한 우승팀 결과는 대회 기간 중에 혹은 경기 종료 후에 공식적으로 알려질 것입니다. 대회가 계획대로 진행된다면 다음과 같은 정보를 기반으로 예상을 할 수 있지만, 최종적으로는 경기 결과에 따라 달라질 수 있으니, 대회 기간 동안 최신 뉴스와 관련 정보를 확인하시는 것이 가장 정확할 것입니다. 

각 나라의 야구 팀들이 얼마나 열심히 준비하고 경기력이 어떻게 발전했는지에 따라 결과가 달라질 수 있으니, 지속적인 추적과 함께 최종 우승 국가의 결정을 기다려보시기 바랍니다.


In [34]:
result = pipe(messages,
              max_new_tokens=200,
              return_full_text=False,
              temperature=1.5,
              top_p=0.3)
print(result[0].get('generated_text'))

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


2026년 아시안 게임의 야구 경기 일정과 결과에 대해 정확히 말씀드리기 위해서는 실제 대회가 진행된 이후의 정보가 필요합니다. 아시안 게임은 매년 개최지가 다르며, 야구 경기의 우승팀은 해당 연도의 대회 결과에 따라 결정됩니다.

현재로선 2026년 아시안 게임이 아직 개최되지 않았거나 정보가 공개되지 않았기 때문에, 정확한 우승팀을 예측하거나 알려드리기 어렵습니다. 아시안 게임의 개최 일정이 확정되면 그에 따른 최신 정보를 제공해 드릴 수 있을 것입니다.

만약 특정 국가나 팀에 대한 관심이 있으시다면, 그 팀의 최근 성적이나 아시안 게임 참가 이력 등을 알려주시면 더 구체적인 정보를 제공해 드릴 수 있습니다!
